services:
  postgres:
    image: postgres:18
    container_name: users-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: users_user
      POSTGRES_PASSWORD: users_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql


volumes:
  postgres_data:
