syntax = "proto3";

package users;

import "google/protobuf/timestamp.proto";

service UserService {
  rpc createUser (CreateUserRequest) returns (PublicUser);
  rpc getById (GetUserByIdRequest) returns (PublicUser);
  rpc getByEmailWithPassword (GetUserByEmailRequest) returns (User);
  rpc updateCurrentUser (UpdateCurrentUserRequest) returns (PublicUser);
}


message CreateUserRequest {
  string name = 1 ;
  string email = 2;
  string passwordHash = 3;

}

message GetUserByIdRequest {
  string userId = 1;
}

enum UserRole {
  USER_ROLE_UNSPECIFIED = 0;
  USER_ROLE_CUSTOMER = 1;
  USER_ROLE_RESTAURANT_OWNER = 2;
  USER_ROLE_DRIVER = 3;
  USER_ROLE_ADMIN = 4;
}

message GetUserByEmailRequest {
  string email = 1;
}

message User {
  string id = 1;
  string name = 2;
  string email = 3;
  string password_hash = 4;
  UserRole role = 5;
  bool is_active = 6;
  google.protobuf.Timestamp created_at = 7;
  google.protobuf.Timestamp updated_at = 8;
}

message PublicUser {
  string id = 1;
  string name = 2;
  string email = 3;
  UserRole role = 4;
  bool is_active = 5;
  google.protobuf.Timestamp created_at = 6;
  google.protobuf.Timestamp updated_at = 7;
}

message UpdateCurrentUserRequest {
  string userId = 1;
  optional string name = 2;
  optional bool isActive = 3;
}
